class Activo {
    constructor(
    Activos_Id_Activo,
    Nombre_Activo,
    Regiones_idRegiones = 1,
    Ciudad,
    Direccion = null,
    Barrio,
    Localidad,
    Piso = null,
    Torre = null,
    Area,
    Imagenes,
    Precio,
    Baños,
    Habitaciones,
    Estrato,
    Conjunto = null,
    Costo_Administracion = null,
    Administracion_Incluida = false,
    Parqueadero = null,
    Tipo_Parqueadero = null,
    Cantidad_Parqueaderos = null,
    Pisos = 1,
    Nombre_Propietario = null,
    Nombre_Arrendatario = null,
    Fecha_Inicio_Arrendamiento = null,
    Fecha_Fin_Arrendamiento = null,
    Estado,
    Antiguedad = null,
    Años = null,
    Observaciones = null
    ) {
      this.Activos_Id_Activo = Activos_Id_Activo,
      this.Nombre_Activo = Nombre_Activo,
      this.Regiones_idRegiones = Regiones_idRegiones,
      this.Ciudad = Ciudad,
      this.Direccion = Direccion,
      this.Barrio = Barrio,
      this.Localidad = Localidad,
      this.Piso = Piso,
      this.Torre = Torre,
      this.Area = Area,
      this.Imagenes = Imagenes,
      this.Precio = Precio,
      this.Baños = Baños,
      this.Habitaciones = Habitaciones,
      this.Estrato = Estrato,
      this.Conjunto = Conjunto,
      this.Costo_Administracion = Costo_Administracion,
      this.Administracion_Incluida = Administracion_Incluida,
      this.Parqueadero = Parqueadero,
      this.Tipo_Parqueadero = Tipo_Parqueadero,
      this.Cantidad_Parqueaderos = Cantidad_Parqueaderos,
      this.Pisos = Pisos,
      this.Nombre_Propietario = Nombre_Propietario,
      this.Nombre_Arrendatario = Nombre_Arrendatario,
      this.Fecha_Inicio_Arrendamiento = Fecha_Inicio_Arrendamiento,
      this.Fecha_Fin_Arrendamiento = Fecha_Fin_Arrendamiento,
      this.Estado = Estado,
      this.Antiguedad = Antiguedad,
      this.Años = Años,
      this.Observaciones = Observaciones
    }
  
    // Método para mostrar información del estudiante
    mostrarInfo() {
      return `Nombrethis.nombre}, Edadthis.edad}, Cursothis.curso}`;
    }
  }